#! /bin/bash

#====================================================
# file: compile.sh
#----------------------------------------------------
# - Compile miniml into a c module
# By Ajhl
#====================================================

Binfold="./bin"
Usage="compile.sh input"
Compiler="src/main.native"
Outfold="out/"


if [[ $# -lt 2 ]];then
    echo $Usage
    exit 2
fi

comptype=$1
input=$2
filename=$(basename "$2" 2> /dev/null) 
extension="${filename##*.}"
base="${filename%.*}"
outputc="${Outfold}${base}.c"
outputh="${Outfold}${base}.h"
outputm="${Outfold}${base}.o"

$Compiler -t $comptype -o $outputc -h $outputh $input > /tmp/tmpfile
res=$?
if [[ $res -ne 0 ]];then
    if [[ $res -eq 5 ]]; then
        echo "MiniML type checker failed"
        exit 2
    else
        echo "MiniML compiler failed"
        #echo "#> Result of :: $outputh"
        #cat $outputh
        #echo "#> Result of :: $outputc"
        #cat $outputc 
        exit 3
    fi
fi

gcc  $outputc -I./lib/ -g -std=c99 -Werror -Wfatal-errors -O -c -o $outputm 

if [[ $? -ne 0 ]];then
    echo "------------------------------------------------------"
    echo "C Compilation failed"
    echo "------------------------------------------------------"
    cat /tmp/tmpfile
    exit 1
fi

exit 0
